---
title: "Regression"
output:
  html_notebook: default
  html_document:
    df_print: paged
  pdf_document: default
---

```{r "loading data", echo=F}
library(ggplot2)
library(ggsci)
library(wesanderson)
library(ggpubr)

library(dplyr)
library(reshape2)

library(formattable)

library(openxlsx)
source("../tools.R")

data_path <- "../../data/output/"
folders_to_comp <- c("classification_restricted/", "classification_full/", "classification_full_higher_lev/")
names_files <- c("restricted", "full", "full and higher-level")

# roc auc
templ_nm <- "result_roc_auc.csv"
roc_data <- data.frame()
for (i in 1:length(folders_to_comp)){
  data <- read.csv(paste0(data_path, folders_to_comp[i], templ_nm), row.names = 1, stringsAsFactors = F)
  data$model_type <- names_files[i]
  roc_data <- rbind.data.frame(roc_data, data)
}

# recall
templ_nm <- "result_recall.csv"
recall_data <- data.frame()
for (i in 1:length(folders_to_comp)){
  data <- read.csv(paste0(data_path, folders_to_comp[i], templ_nm), row.names = 1, stringsAsFactors = F)
  data$model_type <- names_files[i]
  recall_data <- rbind.data.frame(recall_data, data)
}

```


Define baseline
```{r}
map_abb_to_cancer_type <- data.frame(
  abb = c("BRCA", "LIRI", "MALY", "OV", "PACA", "PBCA"),
  cancer_type = c("breast", "liver", "blood", "ovary", "pancreatic", "brain")
)
lift_recall <- data.frame(cancer_type=c("blood", "bone", "brain", "breast", "liver", "ovary", "pancreatic",
                                        "prostate", "skin","uterus"),
                          value=c(1.88235294117647, 3.4108527131783, 4.08268733850129, 5.24904214559387,
                                   3.20561941251596, 4.68710089399744, 4.96807151979566, 4.20178799489144,
                                   2.40102171136654, 2.84802043422733)
                          ) %>% 
  inner_join(map_abb_to_cancer_type) %>% 
  select(-cancer_type) %>% 
  setNames(c("value", "cancer_type")) %>%
  mutate(metric="Lift of recall")

roc_auc <- data.frame(cancer_type=c("blood", "bone", "brain", "breast", "liver", "ovary", "pancreatic",
                                        "prostate", "skin","uterus"),
                          value=c(0.551604075258422, 0.606134077341174, 0.610621197660606, 0.723447610715988,
                                  0.646271778277241, 0.679058565325913, 0.62560466624203, 0.660254262000601,
                                  0.588171472565438, 0.604320388092916)
                          ) %>% 
  inner_join(map_abb_to_cancer_type) %>% 
  select(-cancer_type) %>% 
  setNames(c("value", "cancer_type")) %>%
  mutate(metric="ROC AUC")

pr_auc <- data.frame(cancer_type=c("blood", "bone", "brain", "breast", "liver", "ovary", "pancreatic",
                                        "prostate", "skin","uterus"),
                          value=c(0.014423091728036, 0.021874750855254, 0.02386948560186, 0.035273390432157,
                                  0.02235929989524, 0.027093889264819, 0.044967191192213, 0.027756112492681,
                                  0.016053187079025, 0.018130924874129)
                          ) %>% 
  inner_join(map_abb_to_cancer_type) %>% 
  select(-cancer_type) %>% 
  setNames(c("value", "cancer_type")) %>%
  mutate(metric="PR AUC")

mean_data <- rbind.data.frame(
  lift_recall,
  roc_auc
  )
mean_data <- rbind.data.frame(
  mean_data, 
  pr_auc
  )

```


Plot all metrics

```{r}

pl_values <- rbind.data.frame(
  roc_data %>%
    select(cancer_type, model_type, te_auc) %>%
    setNames(c("cancer_type", "model_type", "value")) %>%
    mutate(
      metric = "ROC AUC"
    ),
    recall_data %>% 
      filter(quantile == "0.03") %>%
      select(cancer_type, model_type, lift_recall) %>%
      setNames(c("cancer_type", "model_type", "value")) %>%
      mutate(
        metric = "Lift of recall"
      )
  )


pl_values <- rbind.data.frame(
  pl_values,
  roc_data %>%
    select(cancer_type, model_type,  pr_auc) %>%
    setNames(c("cancer_type", "model_type", "value")) %>%
    mutate(
      metric = "PR AUC"
    )
)

agg <- pl_values %>%
  group_by(metric, cancer_type, model_type) %>%
  summarize(
    med_val = median(value),
    q75_val = quantile(value, 0.75)
    ) %>%
  arrange(model_type, metric, cancer_type, med_val, q75_val) %>%
  mutate(
    r = row_number()
  )

pl_values <- pl_values %>%
  inner_join(
    agg %>% 
      select(metric, cancer_type, model_type, r), 
    by=c("metric", "cancer_type", "model_type"))


pl_values$model_type <- factor(pl_values$model_type,levels=c("restricted", "full", "full and higher-level"))

g2 <- ggplot(pl_values, aes(y=value, fill=model_type)) + 
  geom_boxplot() +
  facet_grid(metric~cancer_type, scales="free")+
  theme_light()+
  xlab("Model type")+
  ylab("Metric value") +
  labs(fill = "Model type")+
  theme(
    axis.title.x=element_blank(),
    axis.text.x=element_blank(),
    axis.ticks.x=element_blank(),
    text = element_text(size = 9, family = "sans"),
    axis.title.y = element_text(size = 10),
    axis.text.y = element_text(hjust = 1),
    legend.position="bottom", legend.title = element_text(size = 10),    
    ) +
  scale_fill_jco()+
  geom_hline(data=mean_data, aes(yintercept=value))
  
g2
# ggsave(filename = "Fig_classification_r2.tiff", plot = g2, device = "tiff", path = "../../../cancer_breakpoints_hotspots_wide/paper_third/", dpi = 600, units = "in", width = 5, height = 3, scale = 2, compression = "lzw")
```


```{r}
library(ggpubr)
g_f <- ggarrange(g1, g2,  
          labels = c("A", "B"),
          ncol = 1, nrow = 2, heights = c(2, 5),
          font.label = list(size = 10, color = "black", face ="bold"))
g_f
# ggsave(filename = "Fig_benchmark.tiff", plot = g_f, device = "tiff", path = "../../../cancer_breakpoints_hotspots_wide/paper_third/", dpi = 600, units = "in", width = 7, height = 7, scale = 2, compression = "lzw")
```

Save table

```{r echo=F}
# roc auc
roc_data <- roc_data %>%
  mutate(
    train_test_diff = tr_auc - te_auc
  ) %>%
  group_by(cancer_type, model_type) %>%
  summarize(
    min_test_auc = min(te_auc),
    sd_test_auc = sd(te_auc),
    median_test_auc = median(te_auc),
    mean_test_auc = mean(te_auc),
    train_test_diff = mean(train_test_diff),
    n_ex = n(),
    mean_pr_auc = mean(pr_auc),
    sd_pr_auc = sd(pr_auc),
    mean_efron_r2 = mean(efron_r2),
    sd_efron_r2 = sd(efron_r2)
  ) %>%
  mutate(
    ci_lower_roc_auc = mean_test_auc - 1.96 * sd_test_auc / sqrt(n_ex),
    ci_upper_roc_auc = mean_test_auc + 1.96 * sd_test_auc / sqrt(n_ex), 
    ci_lower_pr_auc = mean_pr_auc - 1.96 * sd_pr_auc / sqrt(n_ex),
    ci_upper_pr_auc = mean_pr_auc + 1.96 * sd_pr_auc / sqrt(n_ex),
    ci_lower_r2 = mean_efron_r2 - 1.96 * sd_efron_r2 / sqrt(n_ex),
    ci_upper_r2 = mean_efron_r2 + 1.96 * sd_efron_r2 / sqrt(n_ex), 
  ) %>%
  select(-c("n_ex", "sd_efron_r2", "sd_pr_auc"))


roc_data <- roc_data %>%
  select("cancer_type", "model_type", 
         "min_test_auc", "sd_test_auc", "median_test_auc", "mean_test_auc", "train_test_diff",
         "ci_lower_roc_auc", "ci_upper_roc_auc", "mean_pr_auc", "ci_lower_pr_auc", "ci_upper_pr_auc",
         "mean_efron_r2", "ci_lower_r2", "ci_upper_r2"
         ) %>%
  setNames(c("Cancer type",	"Model type", "Min test ROC AUC",	"SD test ROC AUC",	"Median test ROC AUC",	
             "Mean test ROC AUC", "Train-test difference ROC AUC", "Lower bound of confidence interval for mean test ROC AUC",	
             "Upper bound of confidence interval for mean test ROC AUC", "Mean test PR AUC", 
             "Lower bound of confidence interval for mean test PR AUC",	"Upper bound of confidence interval for mean test PR AUC",
             "Mean test Efron pseudo-R2", "Lower bound of confidence interval for mean test Efron pseudo-R2",
             "Upper bound of confidence interval for mean test Efron pseudo-R2"))

# recall
recall_stats <- recall_data %>%
  mutate(lift_precision = precision / 0.01) %>%
  group_by(cancer_type, model_type, quantile) %>%
  summarize(
    mean_recall = mean(recall),
    mean_lift_recall = mean(lift_recall),
    mean_precision = mean(precision),
    mean_lift_precision = mean(lift_precision),
    sd_recall = sd(recall),
    sd_lift_recall = sd(lift_recall),
    sd_precision = sd(precision),
    sd_lift_precision = sd(lift_precision),
    n_ex = n()
  ) %>%
  mutate(
    ci_lower_recall = mean_recall - 1.96 * sd_recall / sqrt(n_ex),
    ci_upper_recall = mean_recall + 1.96 * sd_recall / sqrt(n_ex),
    
    ci_lower_lift_recall = mean_lift_recall - 1.96 * sd_lift_recall / sqrt(n_ex),
    ci_upper_lift_recall = mean_lift_recall + 1.96 * sd_lift_recall / sqrt(n_ex),    
    
    ci_lower_precision = mean_precision - 1.96 * sd_precision / sqrt(n_ex),
    ci_upper_precision = mean_precision + 1.96 * sd_precision / sqrt(n_ex),       
    
    ci_lower_lift_precision = mean_lift_precision - 1.96 * sd_lift_precision / sqrt(n_ex),
    ci_upper_lift_precision = mean_lift_precision + 1.96 * sd_lift_precision / sqrt(n_ex)
  ) %>% 
  filter(quantile %in% c(0.001, 0.005, 0.01,0.02,0.03, 0.040, 0.050, 0.100)) %>%
  select(
    cancer_type, model_type, quantile, mean_recall, mean_precision, mean_lift_recall, ci_lower_lift_recall,
    ci_upper_lift_recall, mean_lift_precision, ci_lower_lift_precision, ci_upper_lift_precision
    )

recall_stats <- recall_stats %>%
  select(c("quantile", "cancer_type", "model_type", "mean_recall", "mean_lift_recall", "ci_lower_lift_recall",
           "ci_upper_lift_recall",  "mean_precision","mean_lift_precision", "ci_lower_lift_precision", 
           "ci_upper_lift_precision")) %>%
  setNames(c("quantile", "Cancer type",		"Model type", "Mean recall",	"Mean lift of recall",
  "Lower bound of confidence interval for mean lift of recall",	"Upper bound of confidence interval for mean  lift of recall",
  "Mean precision",	"Mean lift of precision",	"Lower bound of confidence interval for mean lift of precision",
  "Upper bound of confidence interval for mean  lift of precision"))

rec_3 <- recall_stats[recall_stats$quantile == 0.03, ] %>% select(-quantile)
rec_5 <- recall_stats[recall_stats$quantile == 0.05, ] %>% select(-quantile)

q3 <- roc_data %>%
  inner_join(
    rec_3, by=c("Cancer type", "Model type")
  )
q5 <- roc_data %>%
  inner_join(
    rec_5, by=c("Cancer type", "Model type")
  )

# wb <- createWorkbook()
# addWorksheet(wb, "q3")
# addWorksheet(wb, "q5")
# 
# writeData(wb, sheet="q3", q3)
# writeData(wb, sheet="q5", q5)
# 
# saveWorkbook(wb, "../../../cancer_breakpoints_hotspots_wide/paper_third/s_benchmark_classification.xlsx", overwrite = T)

```


