---
title: "Regression"
output:
  html_notebook: default
  html_document:
    df_print: paged
  pdf_document: default
---

```{r "loading data", echo=F}
library(ggplot2)
library(ggsci)
library(wesanderson)
library(ggpubr)

library(dplyr)
library(reshape2)

library(formattable)

library(openxlsx)
source("../run/tools.R")

data_path <- "../data/output/"
files_to_comp <- c("regression_restricted.csv", "regression_full_0.csv", "regression_full_1.csv")
names_files <- c("restricted", "full", "full and higher-level")

all_data <- data.frame()
for (i in 1:length(files_to_comp)){
  data <- read.csv(paste0(data_path, files_to_comp[i]), row.names = 1, stringsAsFactors = F)
  data$model_type <- names_files[i]
  all_data <- rbind.data.frame(all_data, data)
}
```

Define baseline
```{r}
benchmark_data <- data.frame(
  cancer_type=c("BRCA", "ESAD", "GACA", "LIRI", "MALY", "OV", "PACA", "PBCA", "RECA"),
  median_val=c(0.18, 0.1, 0.05, 0.1, 0.01, 0.1, 0.04, 0.04, 0.005)
  )
```


Boxplot of Test R2 for all experiments

```{r}
g1 <- ggplot(all_data, aes(y=r_squared_test, fill=reorder(model_type, r_squared_test, mean))) +
  geom_boxplot()+
  facet_wrap(~cancer_type, nrow = 2) +
  scale_fill_jco() + 
  xlab("")+
  ylab("Test R-squared")+
  labs(fill = "Model type")+
  theme_light()+
  theme(
    axis.title.x=element_blank(),
    axis.text.x=element_blank(),
    axis.ticks.x=element_blank(),
    text = element_text(size = 9, family = "sans"),
    axis.title.y = element_text(size = 10),
    axis.text.y = element_text(hjust = 1),
    legend.position="bottom", legend.title = element_text(size = 10),    
    ) +
  geom_hline(data=benchmark_data, aes(yintercept=median_val))
g1

# ggsave(filename = "Fig_regression_r2.tiff", plot = g1, device = "tiff", path = "../../cancer_breakpoints_hotspots_wide/paper_third/", dpi = 600, units = "in", width = 5, height = 3, scale = 2, compression = "lzw")
```

Save table

```{r}
stats <- all_data %>%
  group_by(cancer_type, model_type) %>%
  summarize(
    mean_r_squared_train = mean(r_squared_train),
    mean_rmse_train = mean(rmse_train),
    mean_r_squared_test = mean(r_squared_test),
    mean_rmse_test = mean(rmse_test),    
  ) %>%
  select(c("cancer_type", "model_type", "mean_r_squared_train", "mean_rmse_train", "mean_r_squared_test",
           "mean_rmse_test")) %>%
  setNames(c("Cancer type",	"Model type", "Mean train R-squared",	"Mean test RMSE",
             "Mean test R-squared",	"Mean test RMSE"))

# wb <- createWorkbook()
# addWorksheet(wb, "regression_comparison")
# writeData(wb, sheet="regression_comparison", stats)
# 
# saveWorkbook(wb, "../../cancer_breakpoints_hotspots_wide/paper_third/s_benchmark_regression.xlsx", overwrite = T)
```

